# Generated by Django 3.0.2 on 2020-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200129_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_logo',
            field=models.FileField(default='', upload_to='category_logo'),
            preserve_default=False,
        ),
    ]
