# Generated by Django 3.0.2 on 2020-02-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200201_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Comment'),
        ),
    ]
